# https://github.com/firebase/emulators-codelab/blob/master/.github/workflows/firebase-ci.yaml

name: Frontend and Backend Testing
on: [push, pull_request]
jobs:
  emulator_test:
    name: Run all tests using Firebase Emulator Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: Install dependencies
        run: npm install
        working-directory: functions
      - name: Install Firebase Emulator Suite
        run: npm install -g firebase-tools
        working-directory: functions
      - name: Install Jest
        run: npm install --save-dev jest
        working-directory: functions
      - name: Install playwright
        run: npx playwright install
        working-directory: functions
      - name: Run frontend tests
        run: firebase emulators:exec --project planimation-staging-181bc 'node ./functions/frontend-test/playwright-test.js'
      - name: Run backend tests
        run: firebase emulators:exec --project planimation-staging-181bc --import=./functions/backend-test/__tests__/test_data 'node ./functions/backend-test/test-runner.cjs' 2>&1 | grep -v "i  hosting:\ 127.0.0.1"
      
