name: Run automated tests for all branches
'on':
  push:
    branches:
      - '*'
      
jobs:
  test:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v3.8.1
        - name: Enter test directiory
          run: cd functions
        - name: Start Node.js env
          run: npm run start
        - name: Run Playwright tests
          uses: microsoft/playwright-github-action@v1.5.5
