# https://github.com/firebase/emulators-codelab/blob/master/.github/workflows/firebase-ci.yaml

on: [push, pull_request]
jobs:
  emulator_test:
    name: Run all tests using Firebase Emulator Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: Install Firebase Emulator Suite
        run: npm install -g firebase-tools
      - name: Install Jest
        run: npm install --save-dev jest
      - name: Install playwright
        run: npx playwright install
      - name: Install dependencies
        run: npm install
        working-directory: functions
      - name: Run frontend tests
        run: firebase emulators:exec --project planimation-staging-181bc 'node ./functions/frontend-test/playwright-test.js'
      - name: Run backend tests
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: firebase emulators:exec --project planimation-staging-181bc 'node ./functions/backend-test/test-runner.cjs'
      
